### PR TITLE
Add support for reading and writing bits. Add support for reading multiple memory ares. Migrate to safe Buffer constructor methods

### PR DESCRIPTION
**Pull request by CharlieMarshall**
This replaces PR #17 

Add support for reading bits
Add support for writing bits
Add support for reading multiple memory areas (it handles both bits and words in one command)
Migrate to safe Buffer constructor methods (removes the warning messages)

I have updated the README and exmaples/basic.js to show the usage. I can provide Wireshark logs if you require them.

### CODE REVIEW

**Comment by CharlieMarshall** [comment]
Added support for copying and transferring memory area command tonight. I am not planning on adding any more features to this PR now.

**Comment by ptrks** [comment]
@CharlieMarshall fantastic work! I'll have time to closely look over this PR this evening. If it's not too big of a deal, could you attach a filtered pcap file for each command you added in the comments? I don't have access to the PLCs anymore so it will be the only other way I can verify myself.

Thanks again!

**Comment by CharlieMarshall** [comment]
I emailed you the pcap file. On making the changes I saw that _decodePacket doesn't seem to be used anywhere so I assume it is safe to delete

**Review by ptrks — APPROVED** [review]

**Comment by ptrks** [comment]
@CharlieMarshall I reviewed the pcap file and the changes. Looks great.

Thanks again for your help, it's much appreciated!

**Pull request merged**
